/*
-- Query: SELECT * FROM ole.pur_vndr_addr_t
-- Date: 2014-10-21 09:45
*/
INSERT INTO `pur_vndr_addr_t` (`VNDR_ADDR_GNRTD_ID`,`OBJ_ID`,`VER_NBR`,`VNDR_HDR_GNRTD_ID`,`VNDR_DTL_ASND_ID`,`VNDR_ADDR_TYP_CD`,`VNDR_LN1_ADDR`,`VNDR_LN2_ADDR`,`VNDR_CTY_NM`,`VNDR_ST_CD`,`VNDR_ZIP_CD`,`VNDR_CNTRY_CD`,`VNDR_ATTN_NM`,`VNDR_ADDR_INTL_PROV_NM`,`VNDR_ADDR_EMAIL_ADDR`,`VNDR_B2B_URL_ADDR`,`VNDR_FAX_NBR`,`VNDR_DFLT_ADDR_IND`,`DOBJ_MAINT_CD_ACTV_IND`,`VNDR_ACCOUNT_NBR`,`VNDR_FIN_COA_CD`,`OLE_VNDR_ADDR_NT`) VALUES (12105,'a8106c91-d2d9-4413-b1cc-3f8648ab77d6',1,12105,0,'PO','123 SESAME STREET',NULL,'NEW YORK','NY','10012','US',NULL,NULL,'bobpersing@gmail.com',NULL,NULL,'Y','Y',NULL,NULL,NULL);
