/*
-- Query: SELECT * FROM ole.pur_rcvng_addr_t
-- Date: 2014-10-21 09:42
*/
INSERT INTO `pur_rcvng_addr_t` (`PUR_RCVNG_ADDR_ID`,`OBJ_ID`,`VER_NBR`,`FIN_COA_CD`,`ORG_CD`,`PUR_RCVNG_NM`,`PUR_RCVNG_LN1_ADDR`,`PUR_RCVNG_LN2_ADDR`,`PUR_RCVNG_CTY_NM`,`PUR_RCVNG_ST_CD`,`PUR_RCVNG_PSTL_CD`,`PUR_RCVNG_CNTRY_CD`,`PUR_RCVNG_DFLT_ADDR_IND`,`VNDR_ADDR_USE_RCVNG_IND`,`DOBJ_MAINT_CD_ACTV_IND`) VALUES (1002,'b0df34c5-e010-4608-9b39-81b47d2feb0f',1,'OU',NULL,'OLE UNIVERSITY LIBRARY','ACQUISITIONS DEPT.','1600 PENNSYLVANIA AVENUE','WASHINGTON','DC','20510','US','Y','Y','Y');
