/*
-- Query: SELECT * FROM ole.pur_vndr_hdr_t
-- Date: 2014-10-21 10:04
*/
INSERT INTO `pur_vndr_hdr_t` (`VNDR_HDR_GNRTD_ID`,`OBJ_ID`,`VER_NBR`,`VNDR_TYP_CD`,`VNDR_TAX_NBR`,`VNDR_TAX_TYP_CD`,`VNDR_OWNR_CD`,`VNDR_OWNR_CTGRY_CD`,`VNDR_FWT_BEG_DT`,`VNDR_FWT_END_DT`,`VNDR_W9_RCVD_IND`,`VNDR_W8_BEN_RCVD_IND`,`VNDR_DEBRD_IND`,`VNDR_FRGN_IND`) VALUES (12105,'5cd3fc38-ad1b-4782-8788-db9495eb29c1',1,'PO','',NULL,'CP',NULL,NULL,NULL,NULL,NULL,NULL,'N');
