/*
-- Query: SELECT * FROM ole.pur_ap_cmp_parm_t
-- Date: 2014-10-21 09:04
*/
INSERT INTO `pur_ap_cmp_parm_t` (`CAMPUS_CD`,`OBJ_ID`,`VER_NBR`,`CMP_PUR_DRCTR_NM`,`CMP_PUR_DRCTR_TTL`,`CMP_AP_EMAIL_ADDR`,`PUR_INST_NM`,`PUR_DEPT_NM`,`PUR_DEPT_LN1_ADDR`,`PUR_DEPT_LN2_ADDR`,`PUR_DEPT_CTY_NM`,`PUR_DEPT_ST_CD`,`PUR_DEPT_ZIP_CD`,`PUR_DEPT_CNTRY_CD`,`ACTV_IND`) VALUES ('OL','43135785-9008-449f-b7a0-039a590a39d1',1,NULL,NULL,NULL,'OLE UNIVERSITY','OLE UNIVERSITY LIBRARY','1600 PENNSYLVANIA AVENUE',NULL,'WASHINGTON','DC','20510','US','Y');
