--  *********************************************************************
--  Update Database Script
--  *********************************************************************
--  Change Log: org/kuali/ole/1.5.3.1/db.changelog-20140911.xml
--  *********************************************************************

--  Lock Database
--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_LOAD_KRCR_PARM_T_mysql::ole
SET sql_mode='NO_BACKSLASH_ESCAPES'
/

INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'NUMBER_OF_ITEM_INFO_IN_SINGLE_SOLR_CALL', 'OLE6519', '1', 'CONFG', '100', 'This is for setting the number of item information we can get from a single solr call.The number should be based on the maxhttpheadersize parameter in the tomcats server.xml file.We need to provide the value in a way so that the generated query size should not exceed the size of the maxhttpheadersize.This will be the maximum value for (maxhttpheadersize - 1000)/50', 'A', 'OLE')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOAD_KRCR_PARM_T_mysql', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 1, '7:12359a567ff5fecc39db53a5c3f98f23', 'sql, loadData', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_LOAD_KRMS_TYP_T_mysql::ole
SET sql_mode='NO_BACKSLASH_ESCAPES'
/

INSERT INTO KRMS_TYP_T (TYP_ID, NM, NMSPC_CD, SRVC_NM, ACTV, VER_NBR) VALUES ('OLE2016', 'DeliverNotice', 'OLE', 'deliverNoticeTypeService', 'Y', '1')
/

INSERT INTO KRMS_TYP_T (TYP_ID, NM, NMSPC_CD, SRVC_NM, ACTV, VER_NBR) VALUES ('OLE2017', 'NoticeFormat', 'OLE', 'noticeFormatTypeService', 'Y', '1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOAD_KRMS_TYP_T_mysql', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 2, '7:99ffd5b007110ec9ece6ada89552dd2e', 'sql, loadData', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_T::ole
CREATE TABLE ole.OLE_DLVR_LOAN_NOTICE_T (ID VARCHAR(40) NULL, LOAN_ID VARCHAR(40) NULL, PTRN_ID VARCHAR(37) NULL, NTC_TYP VARCHAR(37) NULL, NTC_SND_TYP VARCHAR(37) NULL, RPLCMNT_FEE_AMNT DECIMAL(8) NULL, NTC_TO_SND_DT TIMESTAMP NULL, VER_NBR DECIMAL(8) NULL, OBJ_ID VARCHAR(36) NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_T', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 3, '7:e731097b4d7108da484a102abd9fcac3', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_PK::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_T ADD PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_PK', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 4, '7:21f505fd8282339c97ab1b98799112c6', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_S::ole
CREATE TABLE ole.OLE_DLVR_LOAN_NOTICE_S (ID VARCHAR(40) NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_S', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 5, '7:fa51791551cfa2046db480ed623bce54', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_S_PK::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_S ADD PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_S_PK', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 6, '7:5754332e190bb4b3bdcb3ade9f33d484', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_S_AUTOINCREMENT::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_S MODIFY ID BIGINT(19) AUTO_INCREMENT
/

ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_S AUTO_INCREMENT=1
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_S_AUTOINCREMENT', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 7, '7:f578d293cfb1ef87911d5284ef8977e9', 'addAutoIncrement', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_T::ole
CREATE TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_T (ID VARCHAR(40) NULL, LOAN_ID VARCHAR(40) NULL, PTRN_ID VARCHAR(37) NULL, NTC_SNT_DT TIMESTAMP NULL, NTC_TYP VARCHAR(37) NULL, NTC_SND_TYP VARCHAR(37) NULL, VER_NBR DECIMAL(8) NULL, OBJ_ID VARCHAR(36) NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_T', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 8, '7:ff18cf6ad84a5b174e648af1d0548e5c', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_PK::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_T ADD PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_PK', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 9, '7:70b1e65eb4179eb0aaae951e64c601b9', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_S::ole
CREATE TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_S (ID VARCHAR(40) NULL)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_S', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 10, '7:af728d0049af377796b8b08ac89339c6', 'createTable', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_S_PK::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_S ADD PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_S_PK', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 11, '7:fa25c7d83f8bb256c296a4b32641cb2f', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

--  Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_S_AUTOINCREMENT::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_S MODIFY ID BIGINT(19) AUTO_INCREMENT
/

ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_S AUTO_INCREMENT=1
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_S_AUTOINCREMENT', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', NOW(), 12, '7:1450fa90adda75f0f43fb5203fb10b46', 'addAutoIncrement', '', 'EXECUTED', '3.2.0')
/

--  Release Database Lock
--  Release Database Lock
