/*
-- Query: SELECT * FROM ole.ca_obj_level_t
-- Date: 2014-10-17 14:21
*/
INSERT INTO `ca_obj_level_t` (`FIN_COA_CD`,`FIN_OBJ_LEVEL_CD`,`OBJ_ID`,`VER_NBR`,`FIN_OBJ_LEVEL_NM`,`FIN_OBJLVL_SHRT_NM`,`FIN_CONS_OBJ_CD`,`FIN_OBJLVL_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','CASH','1e54d14f-ccf9-4da4-8cf4-619f6991a2be',1,'Cash','CASH','MAT','Y','Nu');
INSERT INTO `ca_obj_level_t` (`FIN_COA_CD`,`FIN_OBJ_LEVEL_CD`,`OBJ_ID`,`VER_NBR`,`FIN_OBJ_LEVEL_NM`,`FIN_OBJLVL_SHRT_NM`,`FIN_CONS_OBJ_CD`,`FIN_OBJLVL_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','ELEC','274c6a9f-18cb-4a61-8d89-707a0965dd3c',1,'Electronic material','Electronic','MAT','Y','Nu');
INSERT INTO `ca_obj_level_t` (`FIN_COA_CD`,`FIN_OBJ_LEVEL_CD`,`OBJ_ID`,`VER_NBR`,`FIN_OBJ_LEVEL_NM`,`FIN_OBJLVL_SHRT_NM`,`FIN_CONS_OBJ_CD`,`FIN_OBJLVL_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','MICR','561d40fe-9e55-4056-a973-01db9986c922',1,'Microform materials','Microforms','MAT','Y','Nu');
INSERT INTO `ca_obj_level_t` (`FIN_COA_CD`,`FIN_OBJ_LEVEL_CD`,`OBJ_ID`,`VER_NBR`,`FIN_OBJ_LEVEL_NM`,`FIN_OBJLVL_SHRT_NM`,`FIN_CONS_OBJ_CD`,`FIN_OBJLVL_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','OTHE','21156f00-3a7a-4b63-a364-efffa111fa1f',1,'Other','Other','OTHR','Y','Nu');
INSERT INTO `ca_obj_level_t` (`FIN_COA_CD`,`FIN_OBJ_LEVEL_CD`,`OBJ_ID`,`VER_NBR`,`FIN_OBJ_LEVEL_NM`,`FIN_OBJLVL_SHRT_NM`,`FIN_CONS_OBJ_CD`,`FIN_OBJLVL_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','PRNT','f713a6b0-b8f0-4e96-b856-a68b25c73f9d',1,'Print material','Print materi','MAT','Y','Nu');
