/*
-- Query: SELECT * FROM ole.ca_obj_consoldtn_t
-- Date: 2014-10-17 14:16
*/
INSERT INTO `ca_obj_consoldtn_t` (`FIN_COA_CD`,`FIN_CONS_OBJ_CD`,`OBJ_ID`,`VER_NBR`,`FIN_CONS_OBJ_NM`,`FIN_CONOBJ_SHRT_NM`,`FIN_CONOBJ_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','ASST','fb4dade0-91dc-43e0-a41d-8dd2f4aa62fc',1,'Assets','Assets','Y','03');
INSERT INTO `ca_obj_consoldtn_t` (`FIN_COA_CD`,`FIN_CONS_OBJ_CD`,`OBJ_ID`,`VER_NBR`,`FIN_CONS_OBJ_NM`,`FIN_CONOBJ_SHRT_NM`,`FIN_CONOBJ_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','GEN','a1691669-3d93-4d87-b098-dc3c6ea7db01',1,'General expenditures','General','Y','01');
INSERT INTO `ca_obj_consoldtn_t` (`FIN_COA_CD`,`FIN_CONS_OBJ_CD`,`OBJ_ID`,`VER_NBR`,`FIN_CONS_OBJ_NM`,`FIN_CONOBJ_SHRT_NM`,`FIN_CONOBJ_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','MAT','095750af-3db3-45f7-bff2-0faf5922c2d8',1,'Library Materials','Materials','Y','01');
INSERT INTO `ca_obj_consoldtn_t` (`FIN_COA_CD`,`FIN_CONS_OBJ_CD`,`OBJ_ID`,`VER_NBR`,`FIN_CONS_OBJ_NM`,`FIN_CONOBJ_SHRT_NM`,`FIN_CONOBJ_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','OTHR','1ec670d5-054b-456f-81ac-f0ed20c3e709',1,'Other','Other','Y','NU');
INSERT INTO `ca_obj_consoldtn_t` (`FIN_COA_CD`,`FIN_CONS_OBJ_CD`,`OBJ_ID`,`VER_NBR`,`FIN_CONS_OBJ_NM`,`FIN_CONOBJ_SHRT_NM`,`FIN_CONOBJ_ACTV_CD`,`FIN_REPORT_SORT_CD`) VALUES ('OU','REV','4a712f1d-ad9c-4993-9e3e-80fc5ca9dc79',1,'Revenue','Revenue','Y','02');
