-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: org/kuali/ole/1.5.3.1/db.changelog-20140911.xml
-- *********************************************************************

-- Lock Database
-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_LOAD_KRCR_PARM_T_oracle::ole
INSERT INTO KRCR_PARM_T (NMSPC_CD, CMPNT_CD, PARM_NM, OBJ_ID, VER_NBR, PARM_TYP_CD, VAL, PARM_DESC_TXT, EVAL_OPRTR_CD, APPL_ID) VALUES ('OLE-DLVR', 'Deliver', 'NUMBER_OF_ITEM_INFO_IN_SINGLE_SOLR_CALL', 'OLE6519', '1', 'CONFG', '100', 'This is for setting the number of item information we can get from a single solr call.The number should be based on the maxhttpheadersize parameter in the tomcats server.xml file.We need to provide the value in a way so that the generated query size should not exceed the size of the maxhttpheadersize.This will be the maximum value for (maxhttpheadersize - 1000)/50', 'A', 'OLE')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOAD_KRCR_PARM_T_oracle', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 1, '7:37bf5340305df1533e5067e2d15cba05', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_LOAD_KRMS_TYP_T_oracle::ole
INSERT INTO KRMS_TYP_T (TYP_ID, NM, NMSPC_CD, SRVC_NM, ACTV, VER_NBR) VALUES ('OLE2016', 'DeliverNotice', 'OLE', 'deliverNoticeTypeService', 'Y', '1')
/

INSERT INTO KRMS_TYP_T (TYP_ID, NM, NMSPC_CD, SRVC_NM, ACTV, VER_NBR) VALUES ('OLE2017', 'NoticeFormat', 'OLE', 'noticeFormatTypeService', 'Y', '1')
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_LOAD_KRMS_TYP_T_oracle', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 2, '7:2c2e110d059bc1176e1c8bac63466514', 'loadData', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_T::ole
CREATE TABLE ole.OLE_DLVR_LOAN_NOTICE_T (ID VARCHAR2(40), LOAN_ID VARCHAR2(40), PTRN_ID VARCHAR2(37), NTC_TYP VARCHAR2(37), NTC_SND_TYP VARCHAR2(37), RPLCMNT_FEE_AMNT DECIMAL(8), NTC_TO_SND_DT TIMESTAMP, VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_T', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 3, '7:e731097b4d7108da484a102abd9fcac3', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_PK::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_T ADD CONSTRAINT OLE_DLVR_LOAN_NOTICE_PK PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_PK', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 4, '7:21f505fd8282339c97ab1b98799112c6', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_S::ole
CREATE SEQUENCE ole.OLE_DLVR_LOAN_NOTICE_S START WITH 1 INCREMENT BY 1 ORDER
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_S', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 5, '7:9f7109ea58b7f956c3eb1b5bb39233a3', 'createSequence', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_T::ole
CREATE TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_T (ID VARCHAR2(40), LOAN_ID VARCHAR2(40), PTRN_ID VARCHAR2(37), NTC_SNT_DT TIMESTAMP, NTC_TYP VARCHAR2(37), NTC_SND_TYP VARCHAR2(37), VER_NBR DECIMAL(8), OBJ_ID VARCHAR2(36))
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_T', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 6, '7:ff18cf6ad84a5b174e648af1d0548e5c', 'createTable', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_PK::ole
ALTER TABLE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_T ADD CONSTRAINT OLE_DLVR_LOAN_NOTICE_HSTRY_PK PRIMARY KEY (ID)
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_PK', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 7, '7:70b1e65eb4179eb0aaae951e64c601b9', 'addPrimaryKey', '', 'EXECUTED', '3.2.0')
/

-- Changeset org/kuali/ole/1.5.3.1/db.changelog-20140911.xml::OLE_DLVR_LOAN_NOTICE_HSTRY_S::ole
CREATE SEQUENCE ole.OLE_DLVR_LOAN_NOTICE_HSTRY_S START WITH 1 INCREMENT BY 1 ORDER
/

INSERT INTO DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPTION, COMMENTS, EXECTYPE, LIQUIBASE) VALUES ('OLE_DLVR_LOAN_NOTICE_HSTRY_S', 'ole', 'org/kuali/ole/1.5.3.1/db.changelog-20140911.xml', SYSTIMESTAMP, 8, '7:74a80328aff15a96f03e187f7fa02dec', 'createSequence', '', 'EXECUTED', '3.2.0')
/

-- Release Database Lock
-- Release Database Lock
